# Copyright 2023 brobeson

on:
  workflow_call:
jobs:
  staticAnalysis:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Configure the Build System
        run: cmake -D CMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} -B build
      - name: Build the Software
        run: cmake --build build --parallel $(nproc)
      - name: Run Unit Tests
        run: ctest --test-dir build --parallel $(nproc) --output-on-failure
      #- name: cmake-format lint action
      #  uses: puneetmatharu/cmake-format-lint-action@v1.0.4
      #   with:
      #    args: --check
  #build:
  #  name: A C++ Project
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Clone the repository
  #      uses: actions/checkout@v3
  #    - name: Install Node dependencies
  #      run: npm ci
  #    - name: Check for TypeScript lint
  #      run: npm run lint
  #    - name: Build the project
  #      run: npm run compile
  #    - name: Run the unit tests
  #      run: npm run unitTests
