# Copyright 2023 brobeson

on:
  workflow_call:
jobs:
  staticAnalysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: cmake-format lint action
        uses: puneetmatharu/cmake-format-lint-action@v1.0.4
        with:
          args: --check
  #build:
  #  name: A C++ Project
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Clone the repository
  #      uses: actions/checkout@v3
  #    - name: Install Node dependencies
  #      run: npm ci
  #    - name: Check for TypeScript lint
  #      run: npm run lint
  #    - name: Build the project
  #      run: npm run compile
  #    - name: Run the unit tests
  #      run: npm run unitTests
